name: "Auto Assign PRs"
description: "Assign author, and other specified users, to pull requests when the pull requests are opened, and/or request reviews"
author: "HoutarouOreki"
inputs:
  repo-token:
    description: "A token for the repository"
    required: true
    default: "${{ github.token }}"
  assignees:
    description: "Comma separated list of user names"
    required: false
  reviewers:
    description: "Comma seperated list of user names"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "user-plus"
  color: "red"
